### ISSUE TITLE
conda-build not working

### ISSUE THREAD

**Issue by hoelzer** [hoelzer-lab/hypro#16]
I cloned the current repository and did:

```
conda-build conda_recipe
```

that fails in this step

```yaml
build:
    script: $PYTHON /data/mahlzeitlocal/projects/ma_neander_assembly/hiwi/HyPro/setup.py install --single-version-externally-managed --record=record.txt
```

with the error:

```
...
...
    HyPro 1.0 release

==> git status <==

On branch _conda_cache_origin_head
Your branch is up to date with 'origin/_conda_cache_origin_head'.

nothing to commit, working tree clean

source tree in: /home/martin/miniconda3/conda-bld/hypro_1587107975031/work
export PREFIX=/home/martin/miniconda3/conda-bld/hypro_1587107975031/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
export BUILD_PREFIX=/home/martin/miniconda3/conda-bld/hypro_1587107975031/_build_env
export SRC_DIR=/home/martin/miniconda3/conda-bld/hypro_1587107975031/work
/home/martin/miniconda3/conda-bld/hypro_1587107975031/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python: can't open file '/data/mahlzeitlocal/projects/ma_neander_assembly/hiwi/HyPro/setup.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/martin/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/martin/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/home/martin/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
    verify=args.verify, variants=args.variants)
  File "/home/martin/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/martin/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 2864, in build_tree
    notest=notest,
  File "/home/martin/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 1995, in build
    cwd=src_dir, stats=build_stats)
  File "/home/martin/miniconda3/lib/python3.7/site-packages/conda_build/utils.py", line 404, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/martin/miniconda3/lib/python3.7/site-packages/conda_build/utils.py", line 384, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/martin/miniconda3/conda-bld/hypro_1587107975031/work/conda_build.sh']' returned non-zero exit status 2.
```

I also tried
```yaml
build:
    script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
```

that runs into the same error. 

I am also not sure if the variable ``$PYTHON`` is only resistant on your test system.

**Comment by marlt** [comment]
I try to fix this with the variable "folder" which defines a relative path within the SRC_DIR. So the user just need to redefine the folder value.

**Comment by hoelzer** [comment]
Okay, let me know when I should test this again.

**Comment by marlt** [comment]
The commit fixes should fix the issue, but I couldn use the folder, since this seems not to be a variable definition

**Comment by hoelzer** [comment]
conda-build seems to be working for me now. Please just clean up the master repository

**Comment by marlt** [comment]
Done
