### ISSUE TITLE
File not found error when executed in directory

### ISSUE THREAD

**Issue by hoelzer** [hoelzer-lab/hypro#27]
Hi, it seems that the `.ffn` file is not correctly detected when hypro is executed in the same directory where the `.gff` file is located. For example

```
hypro.py -i PROKKA_06022020.gff -o hypro -f mmseqs2.sh
```

results in 

```
Start HyPro in full mode
hypro
CHECK ARGUMENTS
Current working directory: /home/martin/tmp/myco_final_assemblies/myco3/prokka
Specified input is a file with 'gff' extension.
Check args: outdir is: hypro
Building the output structure...
Done.
Extension will be performed on uniprotkb
Traceback (most recent call last):
  File "/home/martin/miniconda3/envs/hypro/bin/hypro.py", line 774, in <module>
    check_args()
  File "/home/martin/miniconda3/envs/hypro/bin/hypro.py", line 669, in check_args
    print(f"{filename} does not exist. To generate mmseqs2 input query, a 'ffn'-file is required. Make sure, your prokka output is not corrupted.")
NameError: name 'filename' is not defined
```

while the following works

```
hypro.py -i prokka/PROKKA_06022020.gff -o hypro -f mmseqs2.sh
```

**Comment by marlt** [comment]
This should not happen. Thanks for reporting @hoelzer , I will work on this asap and commit when its fixed.

**Comment by hoelzer** [comment]
deprecated bc/ we have a nextflow wf now
